"""Domain types and invariants for The Shittim Chest."""

from shittim_chest.domain.affection import (
    AFFECTION_RULES_VERSION,
    DEFAULT_AFFECTION_SCORE,
    MAX_AFFECTION_SCORE,
    MIN_AFFECTION_SCORE,
    AffectionAssessment,
    AffectionAssessmentStatus,
    AffectionProfile,
    ParticipantAffection,
    assess_affection,
)
from shittim_chest.domain.debate_content import (
    PARTICIPANTS,
    STABLE_TIE_BREAK_ORDER,
    EvidenceBundle,
    EvidenceItem,
    EvidenceSearchStatus,
    FinalDecision,
    FinalProposal,
    InitialOpinion,
    InvalidVote,
    ParticipantSlot,
    SearchRequirement,
    Vote,
    VotingResult,
    select_winner,
)
from shittim_chest.domain.debate_state import (
    DebatePhase,
    DebateState,
    InvalidPhaseTransition,
    InvalidRecoveryTransition,
    InvalidRetryTransition,
    InvalidStateTransition,
    RecoveryState,
)
from shittim_chest.domain.escalation import (
    ESCALATION_RULES_VERSION,
    EscalationAssessment,
    assess_escalation,
)
from shittim_chest.domain.identifiers import AttemptId, DebateId

__all__ = (
    "AFFECTION_RULES_VERSION",
    "DEFAULT_AFFECTION_SCORE",
    "ESCALATION_RULES_VERSION",
    "MAX_AFFECTION_SCORE",
    "MIN_AFFECTION_SCORE",
    "PARTICIPANTS",
    "STABLE_TIE_BREAK_ORDER",
    "AffectionAssessment",
    "AffectionAssessmentStatus",
    "AffectionProfile",
    "AttemptId",
    "DebateId",
    "DebatePhase",
    "DebateState",
    "EscalationAssessment",
    "EvidenceBundle",
    "EvidenceItem",
    "EvidenceSearchStatus",
    "FinalDecision",
    "FinalProposal",
    "InitialOpinion",
    "InvalidPhaseTransition",
    "InvalidRecoveryTransition",
    "InvalidRetryTransition",
    "InvalidStateTransition",
    "InvalidVote",
    "ParticipantAffection",
    "ParticipantSlot",
    "RecoveryState",
    "SearchRequirement",
    "Vote",
    "VotingResult",
    "assess_affection",
    "assess_escalation",
    "select_winner",
)
