"""Create complete, Unicode-range-sharded Web fonts from the pinned originals.

The originals remain the source for server-side OG rendering. Every supported
Unicode character remains available; the common shard only avoids loading the
entire Japanese face to display the interface. No user content is an input.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
from pathlib import Path

import fontTools
from fontTools import subset
from fontTools.ttLib import TTFont

WEB = Path(__file__).resolve().parents[2]
ORIGINALS = WEB / "src/assets/fonts"
OUTPUT = ORIGINALS / "web"
CSS = WEB / "src/styles/fonts.generated.css"
SEED = Path(__file__).with_name("common.txt")
SHARD_SIZE = 256
FACES = (
    ("Regular", 400, "0724ad3f3d0d84b2783eabfbe552f326e56adcfd89c315854640fae480d90601"),
    ("Bold", 700, "bb4008ed0dfce2d74273f2d58d4b3f67c739c0ea23af49825544fea99aa27450"),
    ("ExtraBold", 800, "d37cb0244179cee1bc9d1b46af27437523dedb042d2024d9707990672f5d057a"),
)


def digest(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def unicode_points(font: TTFont) -> set[int]:
    return {point for table in font["cmap"].tables if table.isUnicode() for point in table.cmap}


def common_points() -> set[int]:
    # Keep combining marks in each shard as shaping support. Japanese kana and
    # their combining dakuten/handakuten also stay together in the common face.
    return {ord(char) for char in SEED.read_text(encoding="utf-8")} | {
        point
        for low, high in (
            (0x20, 0xFF),
            (0x300, 0x36F),
            (0x2000, 0x206F),
            (0x3000, 0x30FF),
            (0xFF00, 0xFFEF),
        )
        for point in range(low, high + 1)
    }


def ranges(points: set[int]) -> str:
    values = sorted(points)
    result = []
    index = 0
    while index < len(values):
        start = end = values[index]
        index += 1
        while index < len(values) and values[index] == end + 1:
            end = values[index]
            index += 1
        result.append(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}")
    return ",".join(result)


def parse_ranges(value: str) -> set[int]:
    result = set()
    for part in value.split(","):
        limits = part.removeprefix("U+").split("-")
        low = int(limits[0], 16)
        high = int(limits[-1], 16)
        result.update(range(low, high + 1))
    return result


def css_ranges(points: set[int], common: set[int]) -> str:
    # A CSS range may contain characters absent from the original cmap: the
    # browser then keeps its normal system-font fallback. Include those holes
    # to avoid repeating thousands of tiny descriptors in every font weight.
    # Exclude common characters so all advertised CSS ranges remain disjoint.
    return ranges(points if points == common else set(range(min(points), max(points) + 1)) - common)


def source_font(face: str, expected_digest: str) -> TTFont:
    source = ORIGINALS / f"LINESeedJP-{face}.woff2"
    if digest(source.read_bytes()) != expected_digest:
        raise ValueError(f"Pinned source font differs: {source.name}")
    return TTFont(source, recalcTimestamp=False)


def generate() -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    rules = ["/* Generated by scripts/fonts/generate_fonts.py. Do not edit. */"]
    manifest = {"schemaVersion": 1, "fontTools": fontTools.__version__, "faces": []}
    common = common_points()
    for face, weight, expected_digest in FACES:
        original = source_font(face, expected_digest)
        supported = unicode_points(original)
        primary = common & supported
        remaining = sorted(supported - primary)
        shards = [("common", primary)] + [
            (f"{index // SHARD_SIZE:02d}", set(remaining[index : index + SHARD_SIZE]))
            for index in range(0, len(remaining), SHARD_SIZE)
        ]
        face_manifest = {
            "source": f"LINESeedJP-{face}.woff2",
            "sourceSha256": expected_digest,
            "weight": weight,
            "characterCount": len(supported),
            "shards": [],
        }
        shaping_support = supported & set(range(0x300, 0x370))
        shaping_support |= supported & {0x3099, 0x309A}
        for label, points in shards:
            font = source_font(face, expected_digest)
            options = subset.Options()
            options.layout_features = ["*"]
            options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
            options.name_languages = ["*"]
            options.name_legacy = True
            options.notdef_outline = True
            options.recalc_timestamp = False
            subsetter = subset.Subsetter(options=options)
            subsetter.populate(unicodes=points | shaping_support)
            subsetter.subset(font)
            font.flavor = "woff2"
            stream = io.BytesIO()
            font.save(stream)
            contents = stream.getvalue()
            filename = f"line-seed-jp-{weight}-{label}.woff2"
            outputs[OUTPUT / filename] = contents
            unicode_range = ranges(points)
            css_unicode_range = css_ranges(points, primary)
            face_manifest["shards"].append(
                {
                    "file": filename,
                    "sha256": digest(contents),
                    "bytes": len(contents),
                    "unicodeRange": unicode_range,
                    "cssUnicodeRange": css_unicode_range,
                }
            )
            rules.append(
                f'@font-face {{\n  font-family: "LINE Seed JP";\n'
                f'  src: url("../assets/fonts/web/{filename}") format("woff2");\n'
                f"  font-style: normal;\n  font-weight: {weight};\n  font-display: swap;\n"
                f"  unicode-range: {css_unicode_range};\n}}"
            )
        manifest["faces"].append(face_manifest)
    outputs[CSS] = ("\n\n".join(rules) + "\n").encode()
    manifest["cssSha256"] = digest(outputs[CSS])
    outputs[OUTPUT / "manifest.json"] = (json.dumps(manifest, indent=2) + "\n").encode()
    return outputs


def check() -> None:
    manifest = json.loads((OUTPUT / "manifest.json").read_text())
    for face, _, expected_digest in FACES:
        original = source_font(face, expected_digest)
        supported = unicode_points(original)
        advertised = set()
        advertised_css = set()
        actual = set()
        item = next(
            item for item in manifest["faces"] if item["source"] == f"LINESeedJP-{face}.woff2"
        )
        for shard in item["shards"]:
            path = OUTPUT / shard["file"]
            contents = path.read_bytes()
            if digest(contents) != shard["sha256"] or len(contents) != shard["bytes"]:
                raise ValueError(f"Generated font differs: {path.name}")
            points = parse_ranges(shard["unicodeRange"])
            css_points = parse_ranges(shard["cssUnicodeRange"])
            if advertised_css & css_points or (css_points & supported) != points:
                raise ValueError(f"CSS range ownership differs: {path.name}")
            advertised_css |= css_points
            if advertised & points:
                raise ValueError(f"Overlapping Unicode ranges: {path.name}")
            advertised |= points
            font = TTFont(io.BytesIO(contents), recalcTimestamp=False)
            cmap = unicode_points(font)
            if not points <= cmap:
                raise ValueError(f"Advertised characters missing: {path.name}")
            actual |= cmap
            # Subsetting must not change advance metrics, including uncommon
            # supplementary characters or combining marks from shaping closure.
            source_cmap = original.getBestCmap()
            shard_cmap = font.getBestCmap()
            for point in cmap:
                if original["hmtx"][source_cmap[point]] != font["hmtx"][shard_cmap[point]]:
                    raise ValueError(f"Advance metrics differ: {path.name} U+{point:X}")
        if (
            advertised != supported
            or actual != supported
            or (advertised_css & supported) != supported
        ):
            raise ValueError(f"Unicode coverage differs: {item['source']}")
        if len(advertised) != item["characterCount"]:
            raise ValueError(f"Manifest character count differs: {item['source']}")
        print(f"{item['source']}: all {len(supported)} characters and advance metrics verified")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--check-determinism", action="store_true")
    arguments = parser.parse_args()
    if sum((arguments.write, arguments.check, arguments.check_determinism)) != 1:
        parser.error("choose --write, --check, or --check-determinism")
    if arguments.check:
        check()
        return
    outputs = generate()
    if arguments.check_determinism:
        for path, expected in outputs.items():
            if not path.exists() or path.read_bytes() != expected:
                raise ValueError(f"Generated font output is stale: {path.name}")
        print(f"All {len(outputs)} font outputs are reproducible")
        check()
        return
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for old in OUTPUT.iterdir():
        if old.is_file() and old not in outputs:
            old.unlink()
    for path, contents in outputs.items():
        path.write_bytes(contents)
    print(f"Generated {len(outputs)} font outputs")
    check()


if __name__ == "__main__":
    main()
