"""Deterministic contract generation tests."""

from __future__ import annotations

import json
import re
from pathlib import Path

from shittim_records.generate_contracts import expected_documents, write_or_check


def test_generated_contracts_are_deterministic_and_checkable(tmp_path: Path) -> None:
    write_or_check(tmp_path, check=False)
    first = {path.name: path.read_bytes() for path in sorted(tmp_path.iterdir())}

    write_or_check(tmp_path, check=True)

    assert first == expected_documents()
    assert set(first) == {"openapi.json", "records-api.schema.json", "records-invariants.ts"}
    json_schema = json.loads(first["records-api.schema.json"])
    assert len(json_schema["oneOf"]) == 11
    assert "#/components/schemas/" not in first["records-api.schema.json"].decode()
    assert '"$ref": "#/$defs/ImageAvatarRef"' in first["records-api.schema.json"].decode()
    assert '"$ref": "#/$defs/PlaceholderAvatarRef"' in first["records-api.schema.json"].decode()
    assert '"pattern": "\\\\S"' in first["records-api.schema.json"].decode()
    session_branches = json_schema["$defs"]["SessionResponse"]["anyOf"]
    assert session_branches == [
        {"$ref": "#/$defs/AuthenticatedSession"},
        {"$ref": "#/$defs/AnonymousSession"},
    ]
    detail_properties = json_schema["$defs"]["RecordDetailResponse"]["properties"]
    for collection_name, identity_field in (
        ("participants", "slot"),
        ("initialOpinions", "participant"),
        ("finalProposals", "participant"),
        ("votes", "voter"),
    ):
        assert {
            constraint["contains"]["properties"][identity_field]["const"]
            for constraint in detail_properties[collection_name]["allOf"]
        } == {"participant-a", "participant-b", "participant-c"}
    vote_count_constraints = json_schema["$defs"]["RecordResultSummary"]["properties"][
        "voteCounts"
    ]["allOf"]
    assert {
        constraint["contains"]["properties"]["participant"]["const"]
        for constraint in vote_count_constraints
    } == {"participant-a", "participant-b", "participant-c"}
    assert {
        constraint["if"]["properties"]["voter"]["const"]: constraint["then"]["properties"][
            "candidate"
        ]["not"]["const"]
        for constraint in json_schema["$defs"]["VoteView"]["allOf"]
    } == {
        "participant-a": "participant-a",
        "participant-b": "participant-b",
        "participant-c": "participant-c",
    }
    invariants = first["records-invariants.ts"].decode()
    assert invariants.startswith("// Generated by shittim_records.generate_contracts. Do not edit.")
    assert invariants.count('"participant-a"') == 1
    assert invariants.count('"participant-b"') == 1
    assert invariants.count('"participant-c"') == 1
    assert "export function hasConsistentRecordInvariants" in invariants
    assert "vote.voter === vote.candidate" in invariants
    assert "ballotCounts.get(slot) === summaryCounts.get(slot)" in invariants
    openapi = json.loads(first["openapi.json"])
    assert openapi["info"]["title"] == "Shittim Chest Records API"
    assert set(openapi["paths"]) == {
        "/api/v1/auth/discord/start",
        "/api/v1/auth/discord/callback",
        "/api/v1/session",
        "/api/v1/logout",
        "/api/v1/records",
        "/api/v1/records/{recordId}",
        "/api/v1/insights/rankings",
        "/api/v1/insights/costs",
        "/api/v1/admin/prompts",
        "/api/v1/admin/prompts/apply",
        "/api/v1/admin/prompts/revisions",
        "/api/v1/admin/prompts/revisions/{revision}",
        "/api/v1/admin/prompts/rollback",
        "/api/v1/admin/status",
        "/api/v1/admin/status/refresh",
    }
    assert openapi["paths"]["/api/v1/auth/discord/start"]["get"]["security"] == []
    return_to_schema = openapi["paths"]["/api/v1/auth/discord/start"]["get"]["parameters"][0][
        "schema"
    ]
    return_to_pattern = return_to_schema["pattern"]
    assert re.search(return_to_pattern, "/") is not None
    assert re.search(return_to_pattern, f"/records/{'r' * 43}") is not None
    for unsafe_return_to in (
        "//evil.example",
        r"/\evil.example",
        r"/\\evil.example",
        "/\t/evil.example",
        "/\r/evil.example",
        "/\n/evil.example",
    ):
        assert re.search(return_to_pattern, unsafe_return_to) is None
    assert openapi["paths"]["/api/v1/session"]["get"]["security"] == []
    assert openapi["paths"]["/api/v1/session"]["get"]["parameters"] == [
        {
            "name": "contract",
            "in": "query",
            "required": False,
            "schema": {"type": "string", "enum": ["admin-v1"]},
        }
    ]
    for session_schema in ("AuthenticatedSession", "AnonymousSession"):
        assert "isAdmin" not in json_schema["$defs"][session_schema]["required"]
    assert [
        parameter["name"] for parameter in openapi["paths"]["/api/v1/records"]["get"]["parameters"]
    ] == ["cursor", "limit", "sort", "winner"]
    sort_parameter = openapi["paths"]["/api/v1/records"]["get"]["parameters"][2]["schema"]
    assert sort_parameter == {
        "type": "string",
        "enum": ["newest", "oldest"],
        "default": "newest",
    }
    assert openapi["paths"]["/api/v1/logout"]["post"]["parameters"][0]["name"] == ("X-CSRF-Token")
    apply_operation = openapi["paths"]["/api/v1/admin/prompts/apply"]["post"]
    assert [parameter["name"] for parameter in apply_operation["parameters"]] == [
        "X-CSRF-Token",
        "X-Idempotency-Key",
    ]
    assert apply_operation["requestBody"]["content"]["application/json"]["schema"] == {
        "$ref": "#/components/schemas/AdminPromptApplyRequest"
    }
    assert "AdminPromptRollbackRequest" in openapi["components"]["schemas"]
    prompt_mode_constraints = json_schema["$defs"]["AdminPromptsResponse"]["allOf"]
    assert prompt_mode_constraints == [
        {
            "if": {"properties": {"mode": {"const": "legacy"}}, "required": ["mode"]},
            "then": {
                "properties": {
                    "activeRevision": {"type": "null"},
                    "createdAt": {"type": "null"},
                    "action": {"type": "null"},
                }
            },
        },
        {
            "if": {"properties": {"mode": {"const": "managed"}}, "required": ["mode"]},
            "then": {
                "properties": {
                    "activeRevision": {"type": "string"},
                    "createdAt": {"type": "string"},
                    "action": {"type": "string"},
                }
            },
        },
    ]
    refresh_operation = openapi["paths"]["/api/v1/admin/status/refresh"]["post"]
    assert [parameter["name"] for parameter in refresh_operation["parameters"]] == [
        "X-CSRF-Token",
        "X-Idempotency-Key",
    ]
    for route in (
        "/api/v1/admin/prompts",
        "/api/v1/admin/prompts/apply",
        "/api/v1/admin/prompts/rollback",
        "/api/v1/admin/status",
        "/api/v1/admin/status/refresh",
    ):
        method = "post" if route.endswith(("apply", "rollback", "refresh")) else "get"
        assert {"401", "403", "409"}.issubset(openapi["paths"][route][method]["responses"])
    costs_period = openapi["paths"]["/api/v1/insights/costs"]["get"]["parameters"][0]
    assert costs_period == {
        "in": "query",
        "name": "period",
        "required": False,
        "schema": {
            "type": "string",
            "enum": ["today", "week", "month", "all"],
            "default": "week",
        },
    }
