# SPDX-License-Identifier: MIT
"""Verify a signed, immutable AAB using the official JDK and bundletool."""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import zipfile
from pathlib import Path
from xml.etree import ElementTree

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.serialization import pkcs7

PACKAGE = "dev.pitekusu.shittim.records"
ANDROID = "{http://schemas.android.com/apk/res/android}"


def digest(path: Path) -> str:
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def verify_bundle(
    bundle: Path, bundletool: Path, *, code: int, sha: str, certificate: str
) -> dict[str, object]:
    """The upload certificate is fixed independently of the newly produced AAB."""
    if bundle.is_symlink() or not bundle.is_file() or re.fullmatch(r"[0-9a-f]{40}", sha) is None:
        raise ValueError("android_bundle_input_invalid")
    expected = certificate.replace(":", "").lower()
    if re.fullmatch(r"[0-9a-f]{64}", expected) is None:
        raise ValueError("android_upload_certificate_missing")
    java_home = Path(os.environ["JAVA_HOME"]) / "bin"
    # A pinned self-signed upload certificate raises jarsigner's trust-chain bit
    # (4); unsigned entries use a different bit and are never accepted.
    verified = subprocess.run(  # noqa: S603 - fixed JDK tool, no signing inputs.
        [str(java_home / "jarsigner"), "-J-Duser.language=en", "-verify", "-strict", str(bundle)],
        capture_output=True,
        timeout=90,
        check=False,
    )
    if verified.returncode not in {0, 4} or b"jar verified" not in verified.stdout:
        raise ValueError("android_bundle_signature_invalid")
    with zipfile.ZipFile(bundle) as archive:
        signatures = [
            name
            for name in archive.namelist()
            if re.fullmatch(r"META-INF/[^/]+\.(?:RSA|EC|DSA)", name)
        ]
        if len(signatures) != 1 or archive.getinfo(signatures[0]).file_size > 64 * 1024:
            raise ValueError("android_bundle_signer_invalid")
        certs = pkcs7.load_der_pkcs7_certificates(archive.read(signatures[0]))
        # Current upload key is self-signed. Do not accept a matching public
        # certificate merely appended to an unrelated signer's certificate set.
        if len(certs) != 1 or certs[0].fingerprint(hashes.SHA256()).hex() != expected:
            raise ValueError("android_bundle_signer_invalid")
    pins = json.loads(
        (Path(__file__).resolve().parents[1] / ".github/tool-versions.json").read_text()
    )
    if digest(bundletool) != pins["tools"]["bundletool"]["archive_sha256"]:
        raise ValueError("android_bundletool_digest_invalid")
    manifest = subprocess.run(  # noqa: S603 - digest-pinned official bundletool.
        [
            str(java_home / "java"),
            "-jar",
            str(bundletool),
            "dump",
            "manifest",
            f"--bundle={bundle}",
        ],
        capture_output=True,
        timeout=90,
        check=True,
    )
    # Output is generated by digest-verified bundletool, never an external XML document.
    root = ElementTree.fromstring(manifest.stdout)  # noqa: S314
    application = root.find("application")
    if (
        root.get("package") != PACKAGE
        or root.get(ANDROID + "versionCode") != str(code)
        or root.get(ANDROID + "versionName") != f"0.0.{code}"
        or application is None
        or application.get(ANDROID + "debuggable", "false") != "false"
    ):
        raise ValueError("android_bundle_manifest_invalid")
    return {"sha": sha, "versionCode": code, "bundleSha256": digest(bundle), "track": "internal"}
